name: CI
on: [push]
jobs:
<<<<<<< HEAD
  # Lighthouse step is disabled in sparklayer fork
  # lhci:
  #   name: Lighthouse
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Lighthouse
  #       uses: shopify/lighthouse-ci-action@v1
  #       with:
  #         store: ${{ secrets.SHOP_STORE_OS2 }}
  #         password: ${{ secrets.SHOP_PASSWORD_OS2 }}
  #         access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
  #         product_handle: puppy
  #         collection_handle: all
  #         lhci_github_app_token: ${{ secrets.LHCI_GITHUB_TOKEN }}
||||||| e8083933
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@v1
        with:
          store: ${{ secrets.SHOP_STORE_OS2 }}
          password: ${{ secrets.SHOP_PASSWORD_OS2 }}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          product_handle: puppy
          collection_handle: all
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_TOKEN }}
=======
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@v1.1.1
        with:
          store: ${{ secrets.SHOP_STORE_OS2 }}
          password: ${{ secrets.SHOP_PASSWORD_OS2 }}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          collection_handle: all
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_TOKEN }}
          pull_theme: ${{ secrets.SHOP_PULL_THEME }}
>>>>>>> v10.0.0
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          token: ${{ github.token }}
